version: '3'

services:
  datastore:
    build:
      context: .
      dockerfile: Dockerfile.datastore-emulator
    ports:
      - '8081:8081'
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
      depends_on:
        - datastore
    environment:
      # setting these environment variables will force google cloud
      # datastore library to connect to local datastore emulator
      - DATASTORE_PROJECT_ID=project-test
      - DATASTORE_EMULATOR_HOST=localhost:8081
