name: Test Changes
on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - hotfix/*
    paths:
      - src/*
      - .github/workflows/push.yml
jobs:
  test:
    name: Integration test for Datastore connector
    container: node:12.18.3-alpine3.9
    services:
      datastore:
        image: gavelapis/datastore-emulator-docker:302.0.0
        ports:
          - 8081:8081
    runs-on: ubuntu-latest
    env:
      DATASTORE_PROJECT_ID: project-test
      DATASTORE_EMULATOR_HOST: datastore:8081
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run integraton tests
        run: npm test
